# Generated by Django 4.0.6 on 2022-08-22 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('Sign_Up', 'Sign Up'), ('Forgot_Password', 'Forgot Password')], max_length=30)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('expiry', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
