# Generated by Django 4.0.6 on 2022-08-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmenu',
            old_name='food_type',
            new_name='foodtype',
        ),
        migrations.AddField(
            model_name='restaurantmenu',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
